### ISSUE TITLE
Stop Motion Todo:

### ISSUE THREAD

**Issue by turtletooth** [turtletooth/tahoma#29]
- [x] Make pick work from any tool

- [x] Remove fixed width

- [x] Metadata on test shots

- [x] Does check turn off when an image is captured?
